### ISSUE TITLE
Extension Blog broken by Rich-Text.

### ISSUE THREAD

**Issue by shawny43** [askvortsov1/flarum-rich-text#4]
Same issue at Flarum Blog Issue: https://github.com/v17development/flarum-blog/issues/92#issue-910345657

When Rich Text enabled, that cause tiny box in blog that doesn't supposed happened.
On disabled, the blog return in normal state and working well.

Image of the bug: https://imgur.com/a/RjbDSFu

**Comment by ctml91** [comment]
Some css can get you around that. I think it could probably be implemented on either extension. You might also want to open an issue for the blog extension because it's composer had a "write" and "preview" tab, but the preview is redundant if you are using Rich Text :)

```css
.Flarum-Blog-Composer .ProseMirror.FormControl.Composer-flexible.TextEditor-editor.Post-body{
    min-height: 250px;
}
```
